name: Deploy en VPS

on:
  push:
    branches:
      - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        # Define entorno y clona el repo en el VPS de stagging.
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            #Instalamos sshpass
            - name: Install sshpass
              run: sudo apt-get install sshpass -y
            # Creamos la carpeta .ssh
            - name: Create .ssh directory
              run: mkdir -p ~/.ssh
            # Añadimos el host
            - name: Add remote host to known_hosts
              run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts